### ISSUE TITLE
Installation instructions are broken

### ISSUE THREAD

**Issue by shdown** [NerdyPepper/pista#4]
The following only executes `pista` and sets `PS1` once, on bash startup:
```bash
PS1="$(pista)"    # regular variant
PS1="$(pista -m)" # minimal variant
```

The following tries to execute a binary named `pista -z`, which fails.
```zsh
	PROMPT=$("pista -z")   # `pista -zm` for the miminal variant
```

**Comment by Deluvi** [comment]
Indeed, `"$(pista)"` is evaluated to whatever pista returns, unlike `'$(pista)'` which evaluates to `$(pista)`.

The correct assignment that the doc should indicate is:

```
PS1='$(pista)'    # regular variant
PS1='$(pista -m)' # minimal variant
```

**Comment by oppiliappan** [comment]
whoops! 

it should be 
```shell
"$(pista -z)"
```  

ill fix this with the next commit!

**Comment by filipekiss** [comment]
Hi, I just installed and I'm getting this error when opening a new shell:

```
error: Found argument '-z' which wasn't expected, or isn't valid in this context

USAGE:
    pista [FLAGS]

For more information try --help
```

Is it still needed for the `zsh` setup?

Or just using `pista` is enough?

**Comment by leomwilson** [comment]
@filipekiss still needed, I'm pretty sure I tested it after the fix for bash was pushed. You're getting the error because you need to clone the repo and build from source right now, the maintainer doesn't appear to have updated the crate to the latest git commits, so `cargo install` installs an outdated version.

**Comment by oppiliappan** [comment]
yeah looks like crates has an old version, ill publish `0.1.1` soon!

im a little busy at the moment.

**Comment by oppiliappan** [comment]
i have fixed instructions in the readme as of f2ac2b494b4f5ad87ca83fb256305757b672d7dd, let me know if everything is alright! the new release will be up on crates.io soon!

**Comment by shdown** [comment]
I’m sorry, but have you read my original post and/or the first reply to it?

**Comment by alassek** [comment]
I ran into two problems while attempting to install:
1. simply directing people to rustup.rs to install rust is not sufficient, because it is not obvious you need to run `rustup update` afterward as well
2. the bash instructions are still wrong, thank you @Deluvi for the correct syntax

**Comment by oppiliappan** [comment]
you are right @shdown. to use a command as a prompt, set your PS1 in single quotes, or use `PROMPT_COMMAND`. i will update the instructions accordingly!

**Comment by oppiliappan** [comment]
@alassek i followed the instructions given in [the Cargo book](https://doc.rust-lang.org/cargo/getting-started/installation.html). you should end up with the latest stable release of rust.

**Comment by alassek** [comment]
@NerdyPepper following those instructions do not give you the latest stable version. I got `1.23`.

**Comment by oppiliappan** [comment]
@alassek oh wow. please do take this up with [rustup](https://github.com/rust-lang/rustup.rs/issues). i got `1.36` on a linux vm. 

maybe it has something do with your os/system setup?

**Comment by filipekiss** [comment]
Just noticed the commands for `zsh` say `autoinit` instead of `autoload`, here's a patch for the `README.md`

```diff
diff --git i/README.md w/README.md
index 2b4743c..4ab3918 100644
--- i/README.md
+++ w/README.md
@@ -32,7 +32,7 @@ PS1='$(pista -m)' # minimal variant
 -   zsh users, add this to your `.zshrc`:
 
 ```shell
-autoinit -Uz add-zsh-hook
+autoload -Uz add-zsh-hook
 _pista_prompt() {
 	PROMPT="$(pista -z)"   # `pista -zm` for the miminal variant
 }
```

**Comment by oppiliappan** [comment]
thanks for the fix @filipekiss. i have applied the patch!
